### ISSUE TITLE
Don't install the SDK and compiler if they are already installed

### ISSUE THREAD

**Issue by slaff** [riban-bw/Sming-Release#19]
Check if the ESP_HOME env variable is set and if xtensa-lx106-elf-gcc is in the execution PATH. If that is the case try to compile a small example and if it succeeds do NOT install the SDK and a compile but reuse them.

**Comment by riban-bw** [comment]
Not everyone uses permanent environmental variables and paths so I don't want to do it that way. I may add some command line switches to allow installation of individual modules. I may also add a manifest to allow the installer to know the last versions installed which would allow an upgrade mechanism. I may add individual checks for existence of each of the four modules. One of the switches could be a force option to allow installation without user intervention. The prime goal is to get SMING onto user's machines with least effort. One might argue that if you have already installed it you know how to do it (though this project came about because I struggled each time I tried to install on Windows!)

How does this sound?
